import React, { useCallback, useEffect, useState } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '../components/ui/card';
import { Button } from '../components/ui/button';
import { Badge } from '../components/ui/badge';
import { Alert, AlertDescription } from '../components/ui/alert';
import { FileText, RefreshCw, Eye, Edit, CheckCircle, Clock, AlertCircle } from 'lucide-react';

interface DocumentationSection {
  id: string;
  title: string;
  content: string;
  filePath: string;
  lastModified: number;
  autoGenerated: boolean;
  needsUpdate: boolean;
  codeReferences: string[];
}

interface LivingDocumentationProps {
  apiBase: string;
}

export const LivingDocumentation: React.FC<LivingDocumentationProps> = ({ apiBase }) => {
  const [sections, setSections] = useState<DocumentationSection[]>([]);
  const [isAnalyzing, setIsAnalyzing] = useState(false);
  const [selectedSection, setSelectedSection] = useState<DocumentationSection | null>(null);
  const [isSyncing, setIsSyncing] = useState(false);

  const analyzeCodebase = useCallback(async () => {
    setIsAnalyzing(true);
    try {
      const source = apiBase ? apiBase.replace(/\/$/, '') : 'local';
      // This would integrate with the EvolutionEngine to analyze code
      const mockSections: DocumentationSection[] = [
        {
          id: 'api-overview',
          title: 'API Overview',
          content: `# API Overview

This document provides a comprehensive overview of the Window-AIChat API architecture.
Source: ${source}

## Core Components

### EvolutionEngine
The predictive code evolution system that analyzes patterns and suggests improvements.

### ContextOrchestrator
Manages multi-source context assembly with intelligent scoring.

### VectorStoreService
Handles semantic search and code indexing using embeddings.

## Key Features
- Predictive code evolution
- Real-time context awareness
- Multi-model AI support
- Living documentation system`,
          filePath: '/src/evolve/EvolutionEngine.ts',
          lastModified: Date.now(),
          autoGenerated: true,
          needsUpdate: false,
          codeReferences: ['EvolutionEngine', 'ContextOrchestrator', 'VectorStoreService']
        },
        {
          id: 'component-guide',
          title: 'Component Architecture',
          content: `# Component Architecture Guide

## UI Components

### Core Components
- **EvolveAI**: Main predictive evolution interface
- **LivingDocumentation**: Auto-syncing documentation system
- **EvolutionEngine**: Core analysis and suggestion engine

### Integration Points
The EvolveAI system integrates seamlessly with existing Window-AIChat components:
- AgentLoop for autonomous task execution
- ContextOrchestrator for intelligent context assembly
- VectorStoreService for semantic code search

## Usage Patterns
1. Initialize the EvolutionEngine
2. Analyze codebase patterns
3. Generate predictive insights
4. Apply evolution suggestions`,
          filePath: '/src/evolve/EvolveAI.tsx',
          lastModified: Date.now() - 3600000,
          autoGenerated: true,
          needsUpdate: true,
          codeReferences: ['EvolveAI', 'EvolutionEngine']
        }
      ];
      
      setSections(mockSections);
    } catch (error) {
      console.error('[LivingDocumentation] Failed to analyze codebase:', error);
    } finally {
      setIsAnalyzing(false);
    }
  }, [apiBase]);

  useEffect(() => {
    void analyzeCodebase();
  }, [analyzeCodebase]);

  const syncDocumentation = async () => {
    setIsSyncing(true);
    try {
      // This would trigger real-time documentation sync
      await new Promise(resolve => setTimeout(resolve, 2000));
      
      setSections(prev => prev.map(section => ({
        ...section,
        lastModified: Date.now(),
        needsUpdate: false
      })));
    } catch (error) {
      console.error('[LivingDocumentation] Failed to sync:', error);
    } finally {
      setIsSyncing(false);
    }
  };

  const getStatusIcon = (section: DocumentationSection) => {
    if (section.needsUpdate) {
      return <AlertCircle className="h-4 w-4 text-yellow-500" />;
    }
    return <CheckCircle className="h-4 w-4 text-green-500" />;
  };

  const getStatusBadge = (section: DocumentationSection) => {
    if (section.needsUpdate) {
      return <Badge variant="secondary">Needs Update</Badge>;
    }
    if (section.autoGenerated) {
      return <Badge variant="outline">Auto-Generated</Badge>;
    }
    return <Badge variant="default">Manual</Badge>;
  };

  const formatLastModified = (timestamp: number) => {
    const date = new Date(timestamp);
    const now = new Date();
    const diffMs = now.getTime() - date.getTime();
    const diffMins = Math.floor(diffMs / 60000);
    
    if (diffMins < 1) return 'Just now';
    if (diffMins < 60) return `${diffMins}m ago`;
    if (diffMins < 1440) return `${Math.floor(diffMins / 60)}h ago`;
    return `${Math.floor(diffMins / 1440)}d ago`;
  };

  if (isAnalyzing) {
    return (
      <div className="flex items-center justify-center p-8">
        <div className="text-center">
          <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-blue-600 mx-auto mb-4"></div>
          <p className="text-gray-600">Analyzing codebase for documentation...</p>
        </div>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-2xl font-bold flex items-center gap-2">
            <FileText className="h-6 w-6 text-blue-500" />
            Living Documentation
          </h2>
          <p className="text-gray-600 mt-1">
            Auto-syncing documentation that evolves with your codebase
          </p>
        </div>
        <div className="flex gap-2">
          <Button
            onClick={syncDocumentation}
            disabled={isSyncing}
            variant="outline"
            className="flex items-center gap-2"
          >
            <RefreshCw className={`h-4 w-4 ${isSyncing ? 'animate-spin' : ''}`} />
            {isSyncing ? 'Syncing...' : 'Sync Now'}
          </Button>
          <Button onClick={analyzeCodebase} variant="outline">
            Refresh Analysis
          </Button>
        </div>
      </div>

      {/* Summary Stats */}
      <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
        <Card>
          <CardContent className="p-4">
            <div className="flex items-center gap-2">
              <FileText className="h-5 w-5 text-blue-500" />
              <div>
                <p className="text-sm text-gray-600">Total Sections</p>
                <p className="text-2xl font-bold">{sections.length}</p>
              </div>
            </div>
          </CardContent>
        </Card>
        
        <Card>
          <CardContent className="p-4">
            <div className="flex items-center gap-2">
              <CheckCircle className="h-5 w-5 text-green-500" />
              <div>
                <p className="text-sm text-gray-600">Up to Date</p>
                <p className="text-2xl font-bold">
                  {sections.filter(s => !s.needsUpdate).length}
                </p>
              </div>
            </div>
          </CardContent>
        </Card>
        
        <Card>
          <CardContent className="p-4">
            <div className="flex items-center gap-2">
              <AlertCircle className="h-5 w-5 text-yellow-500" />
              <div>
                <p className="text-sm text-gray-600">Needs Update</p>
                <p className="text-2xl font-bold">
                  {sections.filter(s => s.needsUpdate).length}
                </p>
              </div>
            </div>
          </CardContent>
        </Card>
        
        <Card>
          <CardContent className="p-4">
            <div className="flex items-center gap-2">
              <RefreshCw className="h-5 w-5 text-purple-500" />
              <div>
                <p className="text-sm text-gray-600">Auto-Generated</p>
                <p className="text-2xl font-bold">
                  {sections.filter(s => s.autoGenerated).length}
                </p>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>

      {/* Documentation Sections */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Section List */}
        <div className="lg:col-span-1 space-y-4">
          <Card>
            <CardHeader>
              <CardTitle>Documentation Sections</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="space-y-3">
                {sections.map((section) => (
                  <div
                    key={section.id}
                    className={`p-3 border rounded-lg cursor-pointer transition-colors ${
                      selectedSection?.id === section.id 
                        ? 'border-blue-500 bg-blue-50' 
                        : 'border-gray-200 hover:bg-gray-50'
                    }`}
                    onClick={() => setSelectedSection(section)}
                  >
                    <div className="flex items-start justify-between mb-2">
                      <h4 className="font-medium text-sm">{section.title}</h4>
                      {getStatusIcon(section)}
                    </div>
                    <div className="flex items-center gap-2 mb-2">
                      {getStatusBadge(section)}
                    </div>
                    <div className="flex items-center gap-1 text-xs text-gray-500">
                      <Clock className="h-3 w-3" />
                      {formatLastModified(section.lastModified)}
                    </div>
                    <div className="text-xs text-gray-500 mt-1">
                      {section.filePath.split('/').pop()}
                    </div>
                  </div>
                ))}
              </div>
            </CardContent>
          </Card>
        </div>

        {/* Content Viewer */}
        <div className="lg:col-span-2">
          {selectedSection ? (
            <Card>
              <CardHeader>
                <div className="flex items-center justify-between">
                  <CardTitle className="flex items-center gap-2">
                    <Eye className="h-5 w-5" />
                    {selectedSection.title}
                  </CardTitle>
                  <div className="flex items-center gap-2">
                    {getStatusBadge(selectedSection)}
                    <Button size="sm" variant="outline">
                      <Edit className="h-4 w-4 mr-1" />
                      Edit
                    </Button>
                  </div>
                </div>
              </CardHeader>
              <CardContent>
                <div className="prose prose-sm max-w-none">
                  <div className="bg-gray-50 p-4 rounded-lg">
                    <pre className="whitespace-pre-wrap text-sm text-gray-700">
                      {selectedSection.content}
                    </pre>
                  </div>
                </div>
                
                {selectedSection.codeReferences.length > 0 && (
                  <div className="mt-6">
                    <h4 className="font-medium text-sm mb-2">Code References:</h4>
                    <div className="flex flex-wrap gap-1">
                      {selectedSection.codeReferences.map((ref, idx) => (
                        <Badge key={idx} variant="secondary" className="text-xs">
                          {ref}
                        </Badge>
                      ))}
                    </div>
                  </div>
                )}
                
                <div className="mt-6 pt-4 border-t text-xs text-gray-500">
                  Last updated: {formatLastModified(selectedSection.lastModified)}
                  {selectedSection.autoGenerated && ' • Auto-generated'}
                </div>
              </CardContent>
            </Card>
          ) : (
            <Card>
              <CardContent className="p-8 text-center">
                <FileText className="h-12 w-12 text-gray-400 mx-auto mb-4" />
                <h3 className="text-lg font-semibold text-gray-700 mb-2">
                  Select a documentation section
                </h3>
                <p className="text-gray-500">
                  Choose a section from the list to view its content and details.
                </p>
              </CardContent>
            </Card>
          )}
        </div>
      </div>

      {/* Sync Status Alert */}
      {sections.filter(s => s.needsUpdate).length > 0 && (
        <Alert>
          <AlertCircle className="h-4 w-4" />
          <AlertDescription>
            {sections.filter(s => s.needsUpdate).length} documentation sections need updates. 
            Click "Sync Now" to automatically update them based on the latest code changes.
          </AlertDescription>
        </Alert>
      )}
    </div>
  );
};

export default LivingDocumentation;
